#!/usr/bin/env php
<?php

require_once 'Console/CommandLine.php';

Varnish::fromInput();

class Varnish
{
    private $__varnish_flag = '/var/www/default/varnish-enabled';

    public $task;

    public function __construct($task)
    {
        $this->task = $task;
    }

    public static function fromInput()
    {
        $parser = new Console_CommandLine();
        $parser->description = "Manage Varnish from the command line";

        $parser->addArgument('task', array(
            'description' => 'enable|disable|purge',
            'help_name'   => 'TASK'
        ));

        try
        {
            $result   = $parser->parse();
            $task     = $result->args['task'];

            $instance = new self($task);
            $instance->run();
        } catch (Exception $e) {
            $parser->displayError($e->getMessage());
        }
    }

    public function run()
    {
        try
        {
            $task = $this->task;
            $this->$task();
        }
        catch (Exception $e) {
            $this->error($e->getMessage());
        }
    }

    public function enable()
    {
        if (!file_exists($this->__varnish_flag)) {
            `sudo touch $this->__varnish_flag`;
        }

        $this->purge();
    }

    public function disable()
    {
        if (file_exists($this->__varnish_flag)) {
            `sudo rm $this->__varnish_flag`;
        }

        $this->purge();
    }

    public function purge()
    {
        `sudo varnishadm -T 127.0.0.1:6082 -S /etc/varnish/secret "ban req.url ~ ."`;
    }
}
