#!/usr/bin/env php
<?php

require_once 'Console/CommandLine.php';

XDebug::fromInput();

class XDebug
{
    public $task;

    protected $_ini_files = array('/etc/php5/cli/conf.d/zzz_xdebug.ini', '/etc/php5/fpm/conf.d/zzz_xdebug.ini', '/etc/php5/conf.d/zzz_xdebug.ini');

    public function __construct($task)
    {
        $this->task       = $task;
    }

    public static function fromInput()
    {
        $parser = new Console_CommandLine();
        $parser->description = "Manage XDebug through the command line";

        $parser->addArgument('task', array(
            'description' => 'enable|disable',
            'help_name'   => 'TASK'
        ));

        try
        {
            $result   = $parser->parse();
            $task     = $result->args['task'];

            $instance = new self($task);
            $instance->run();
        } catch (Exception $e) {
            $parser->displayError($e->getMessage());
        }
    }

    public function run()
    {
        try
        {
            $task = $this->task;
            $this->$task();
        }
        catch (Exception $e) {
            $this->error($e->getMessage());
        }
    }

    public function enable()
    {
        foreach ($this->_ini_files as $file)
        {
            if (file_exists($file)) {
                `sudo sed -i 's#^;\s*zend_extension=#zend_extension=#' $file`;
            }
        }

        `sudo /etc/init.d/nginx restart`;
    }

    public function disable()
    {
        foreach ($this->_ini_files as $file)
        {
            if (file_exists($file)) {
                `sudo sed -i 's#^zend_extension=#; zend_extension=#' $file`;
            }
        }

        `sudo /etc/init.d/nginx restart`;
    }
}